### ISSUE TITLE
No examples given!

### ISSUE THREAD

**Issue by kp625544** [mudassirkhan19/cricinfo-ballwise-scraper#1]
Can you specify an example as what to specify in the excel file! an example excel file would work too! Thanks

**Comment by mudassirkhan19** [comment]
I did specify the columns you need in the readme :

"You can modify it as you want to suit your needs. It requires a csv file with each row of match data you want to scrape and atleast two columns:

Link for scorecard
Link for first innings commentary" 

'scorecard', 'comm_inn_1' and 'note' are the three columns you require. Keep the note column empty if you want the particular entry to be scraped. Or else just comment out the line of code which checks whether the note column is empty and not include that column in your csv file.

**Comment by mudassirkhan19** [comment]
I have included the sample excel file now. Hope it helps!
